### ISSUE TITLE
Error in before_insert()

### ISSUE THREAD

**Issue by defenda** [dirtyfilthy/freshonions-torscraper#22]
Harvest is working well, but trying to use push.sh I got the message below:

2018-05-04 14:37:58 [scrapy.core.scraper] ERROR: Spider error processing <GET http://oxwugzccvk3dk6tj.onion/index.html> (referer: None)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/spidermiddlewares/offsite.py", line 30, in process_spider_output
    for x in result:
  File "/root/freshonions/torscraper/middlewares.py", line 192, in <genexpr>
    return (_set_range(r) for r in result or ())
  File "/usr/local/lib/python2.7/dist-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/usr/local/lib/python2.7/dist-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/usr/local/lib/python2.7/dist-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/core.py", line 533, in new_gen_func
    output = wrapped_interact(iterator)
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/core.py", line 520, in wrapped_interact
    rollback_and_reraise(sys.exc_info())
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/core.py", line 320, in rollback_and_reraise
    reraise(*exc_info)
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/core.py", line 510, in wrapped_interact
    output = interact(iterator, input, exc_info)
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/core.py", line 484, in interact
    return next(iterator) if input is None else iterator.send(input)
  File "/root/freshonions/torscraper/spiders/tor_scrapy.py", line 323, in parse
    page = self.update_page_info(response.url, title, response.status, is_frontpage, size)
  File "<auto generated wrapper of update_page_info() function>", line 2, in update_page_info
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/core.py", line 460, in new_func
    try: return func(*args, **kwargs)
  File "/root/freshonions/torscraper/spiders/tor_scrapy.py", line 230, in update_page_info
    page = Page.get(url=url)
  File "<auto generated wrapper of get() function>", line 2, in get
  File "/usr/local/lib/python2.7/dist-packages/pony/utils/utils.py", line 58, in cut_traceback
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/core.py", line 3702, in get
    try: return entity._find_one_(kwargs)  # can throw MultipleObjectsFoundError
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/core.py", line 3801, in _find_one_
    if obj is None: obj = entity._find_in_db_(avdict, unique, for_update, nowait)
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/core.py", line 3860, in _find_in_db_
    cursor = database._exec_sql(sql, arguments)
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/core.py", line 813, in _exec_sql
    connection = cache.prepare_connection_for_query_execution()
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/core.py", line 1651, in prepare_connection_for_query_execution
    if not cache.noflush_counter and cache.modified: cache.flush()
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/core.py", line 1728, in flush
    if obj is not None: obj._before_save_()
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/core.py", line 5049, in _before_save_
    if status == 'created': obj.before_insert()
  File "/root/freshonions/lib/tor_db/models/domain.py", line 155, in before_insert
    dom.save()
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch_dsl/document.py", line 437, in save
    return meta['created']

**Comment by davisbra** [comment]
for running push.sh, in 'scripts' directory, you should enter a domain as below: 
./push.sh http://oxwugzccvk3dk6tj.onion
also, it seems that your database setting has problem, can you share your database setting in /etc/database?

**Comment by L3houx** [comment]
Like @davisbra  said, you need to pass an onion domain as parameters. If you still have problems linked to some functionality, just take a look at our forked project: https://github.com/GoSecure/freshonions-torscraper
